/**
 * This class is generated by jOOQ
 */
package com.abcijkxyz.jooq.model;


import com.abcijkxyz.jooq.model.tables.Author;
import com.abcijkxyz.jooq.model.tables.Book;
import com.abcijkxyz.jooq.model.tables.BookAuthorRel;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mydb extends SchemaImpl {

	private static final long serialVersionUID = -1264462009;

	/**
	 * The reference instance of <code>mydb</code>
	 */
	public static final Mydb MYDB = new Mydb();

	/**
	 * No further instances allowed
	 */
	private Mydb() {
		super("mydb");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Author.AUTHOR,
			Book.BOOK,
			BookAuthorRel.BOOK_AUTHOR_REL);
	}
}
