/**
 * This class is generated by jOOQ
 */
package com.abcijkxyz.jooq.model;


import com.abcijkxyz.jooq.model.tables.Author;
import com.abcijkxyz.jooq.model.tables.Book;
import com.abcijkxyz.jooq.model.tables.BookAuthorRel;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mydb
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table mydb.author
	 */
	public static final Author AUTHOR = com.abcijkxyz.jooq.model.tables.Author.AUTHOR;

	/**
	 * The table mydb.book
	 */
	public static final Book BOOK = com.abcijkxyz.jooq.model.tables.Book.BOOK;

	/**
	 * The table mydb.book_author_rel
	 */
	public static final BookAuthorRel BOOK_AUTHOR_REL = com.abcijkxyz.jooq.model.tables.BookAuthorRel.BOOK_AUTHOR_REL;
}
